fields = {
    "Project ID	": "",
    "Name	": "moped_project.project_name",
    "Project Notes	": "moped_proj_notes.project_note",
    "Current Phase	": "",
    "Project Type	": "",
    "Funding	": "",
    "Project Sponsor	": "",
    "Signals	": "",
    "Modified Date	": "",
    "Modified By	": "",
    "Task Order	": "",
    "Contractor/Contract	": "",
    "External Status Note	": "",
    "Internal Status Note	": "",
    "Project DO #	": "",
    "Work Assignment ID	": "",
    "Unit	": "",
    "Fund	": "",
    "Targeted Construction Start	": "",
    "Project Completion Date	": "",
    "Designer	": "",
    "Inspector": "",
}
