-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DELETE FROM public.moped_proj_phases where phase_id = 0;
-- DELETE FROM public.moped_phases where phase_id = 0;
