-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE moped_proj_component_tags ADD CONSTRAINT unique_component_and_tag UNIQUE ("project_component_id", "component_tag_id");
