services:
  arcgis:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: python /app/components_to_agol.py
    command: -d
    environment:
      - AGOL_USERNAME=${AGOL_USERNAME}
      - AGOL_PASSWORD=${AGOL_PASSWORD}
      - HASURA_ENDPOINT=${HASURA_ENDPOINT}
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}