ALTER TABLE "public"."feature_signals" ALTER COLUMN "signal_id" SET NOT NULL;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "location_name" SET NOT NULL;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "signal_type" SET NOT NULL;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "geography" DROP DEFAULT;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "geography" SET NOT NULL;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "knack_id" SET NOT NULL;
ALTER TABLE "public"."feature_signals" ALTER COLUMN "component_id" SET NOT NULL;
ALTER TABLE "public"."features" ALTER COLUMN "component_id" SET NOT NULL;
ALTER TABLE "public"."features" DROP COLUMN name;
ALTER TABLE "public"."feature_street_segments" DROP COLUMN knack_id, DROP COLUMN project_extent_id, DROP COLUMN render_type;
ALTER TABLE "public"."feature_intersections" DROP COLUMN project_extent_id, DROP COLUMN render_type;
ALTER TABLE "public"."feature_drawn_lines" DROP COLUMN render_type;
ALTER TABLE "public"."feature_drawn_points" DROP COLUMN render_type;
