DELETE FROM moped_components_subcomponents where 1=1;

INSERT INTO moped_components_subcomponents (component_id, subcomponent_id)
    values
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'PHB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Accessible pedestrian signal (APS)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'RRFB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Accessible pedestrian signal (APS)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Accessible pedestrian signal (APS)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'PHB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Bicycle accommodations at PHB')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Bicycle signal (standard signal + bicycle signal sign)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Bicycle signal face (experiment)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Bicycle signal face (interim approval)')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Continuous flow intersection')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Curb extension')),
((SELECT component_id FROM moped_components WHERE component_name = 'Refuge Island' AND component_subtype = 'Bike'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Curb extension')),
((SELECT component_id FROM moped_components WHERE component_name = 'Refuge Island' AND component_subtype = 'Bike/Ped'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Curb extension')),
((SELECT component_id FROM moped_components WHERE component_name = 'Refuge Island' AND component_subtype = 'Ped'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Curb extension')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'PHB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Detection - Bicycle')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'RRFB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Detection - Bicycle')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Detection - Bicycle')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Detection - vehicle')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Intersection square-up')),
((SELECT component_id FROM moped_components WHERE component_name = 'Sig/nal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Leading bicycle interval')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Leading pedestrian interval')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'PHB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Pedestrian signal head and pushbuttons')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Protected intersection - Full')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Protected intersection - Full - Shared use')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Protected intersection - partial')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Protected left turn phase')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Radius tightening')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Slip lane removal')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Smart right')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'PHB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Timing adjustment')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'RRFB'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Timing adjustment')),
((SELECT component_id FROM moped_components WHERE component_name = 'Signal' AND component_subtype = 'Traffic'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Timing adjustment')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Transit corner modification')),
((SELECT component_id FROM moped_components WHERE component_name = 'Intersection' AND component_subtype = 'Improvement'),(SELECT subcomponent_id FROM moped_subcomponents WHERE subcomponent_name = 'Vehicle lane reconfiguration'));
