update moped_tags set is_deleted = false where slug = 'map_signals2023';
update moped_tags set is_deleted = false where slug = 'map_transitenhancement2023';
update moped_tags set is_deleted = false where slug = 'map_vzero_systemicsafety_curves2023';
update moped_tags set is_deleted = false where slug = 'map_vzero_intersectionspotential2023';
update moped_tags set is_deleted = false where slug = 'map_vzero_intersections2023';
update moped_tags set is_deleted = false where slug = 'map_vzero_speedmanagement2023';
delete from moped_tags where slug = 'map-transit-speed-and-reliability-capmetro-ila';
delete from moped_tags where slug = 'map-transit-enhancement';
delete from moped_tags where slug = 'map-vision-zero-major-safety';
delete from moped_tags where slug = 'map-vision-zero-ped-safety';
delete from moped_tags where slug = 'map-vision-zero-rapid-response-small-scale';
delete from moped_tags where slug = 'map-vision-zero-signal-safety';
delete from moped_tags where slug = 'map-vision-zero-speed-management';
delete from moped_tags where slug = 'map-vision-zero-street-lighting';
delete from moped_tags where slug = 'map-vision-zero-systemic-safety';
delete from moped_tags where slug = 'map-vision-zero-systemic-safety-access-management';
delete from moped_tags where slug = 'map-vision-zero-systemic-safety-curve-warnings';
