-- we cannot apply this migration until after this column is removed from 
-- as a tracked column on the hasura event trigger for moped_proj_phases.
-- otherwise, the subsequent migrations will fail because their triggers
-- will look for a column that doesn't exist. it's quite a gotcha actually
-- because our CI applies metadata after migrations, we cannot do these
-- two tasks in one release. it has to go like this:
-- first release: remove `subphase_name` from the moped_proj_phases event
-- sescond release: safely drop this column.
--
-- alter table "public"."moped_proj_phases" drop column "subphase_name" cascade;
select 0;
