INSERT INTO moped_components (component_name, component_subtype, line_representation,feature_layer_id) VALUES
    ('Bike lane','Ramp to Sidewalk',TRUE,4),
    ('Bike Lane','Advisory',TRUE,4),
    ('Shared Street',null,TRUE,4),
    ('Green Infrastructure','Rain Garden',FALSE,5),
    ('Green Infrastructure','Vegetated Channel',FALSE,5),
    ('Neighborhood Bikeway',null,TRUE,4),
    ('Roadway',null,TRUE,4),
    ('Pedestrian','Park and Walk',FALSE,5),
    ('Pedestrian','Crossing Improvements',FALSE,5),
    ('Pedestrian','Zone',TRUE,4),
    ('Roadway','Shoulder',TRUE,4),
    ('Signage','In-street Yield to Pedestrians',TRUE,4),
    ('Roadway','Widening',TRUE,4),
    ('Trail','Bridge',TRUE,4),
    ('Trail','Curb Ramps',TRUE,4),
    ('Trail','Grade Separated Crossing',TRUE,4),
    ('Trail','Low Water Crossing',TRUE,4),
    ('Trail','Shared Use Path (Paved In-Street)',TRUE,4),
    ('Trail','Shared Use Path (Paved)',TRUE,4),
    ('Trail','Shared Use Path (Paved One-Way Bike)',TRUE,4),
    ('Trail','Tunnel',TRUE,4),
    ('Trail','Unpaved',TRUE,4),
    ('Sidewalk','Improvements',TRUE,4);
