export const projectPoints = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {
        component_id: 23,
        component_name: "Pavement Marking",
        component_subtype: "Crossbike",
        moped_subcomponents: "",
        project_id: 156,
        project_description: "john's latest project",
        capitally_funded: false,
        completion_end_date: null,
        construction_start_date: null,
        current_phase: "",
        current_status: "active",
        date_added: "2021-01-07T23:21:38.359434+00:00",
        ecapris_subproject_id: 123456,
        end_date: null,
        fiscal_year: "2020",
        funding_source_name: null,
        is_deleted: false,
        milestone_id: null,
        project_designer: null,
        project_inspector: null,
        project_length: 87,
        project_name: "john's latest project",
        project_note: null,
        project_order: null,
        project_partner: null,
        project_sponsor: "None",
        project_team_members: null,
        status_id: 0,
        status_name: null,
        task_order_name: null,
        timeline_id: null,
        type_name: null,
        updated_at: "2022-03-01T23:37:23.289045+00:00",
      },
      geometry: {
        type: "MultiPoint",
        coordinates: [[-97.74881668388844, 30.271808630864342]],
      },
    },
    {
      type: "Feature",
      properties: {
        component_id: 18,
        component_name: "Signal",
        component_subtype: "Traffic",
        moped_subcomponents:
          "Audible push button, Bicycle signal, Leading pedestrian interval",
        project_id: 156,
        project_description: "john's latest project",
        capitally_funded: false,
        completion_end_date: null,
        construction_start_date: null,
        current_phase: "",
        current_status: "active",
        date_added: "2021-01-07T23:21:38.359434+00:00",
        ecapris_subproject_id: 123456,
        end_date: null,
        fiscal_year: "2020",
        funding_source_name: null,
        is_deleted: false,
        milestone_id: null,
        project_designer: null,
        project_inspector: null,
        project_length: 87,
        project_name: "john's latest project",
        project_note: null,
        project_order: null,
        project_partner: null,
        project_sponsor: "None",
        project_team_members: null,
        status_id: 0,
        status_name: null,
        task_order_name: null,
        timeline_id: null,
        type_name: null,
        updated_at: "2022-03-01T23:37:23.289045+00:00",
      },
      geometry: { type: "MultiPoint", coordinates: [[-97.749527, 30.269945]] },
    },
    {
      type: "Feature",
      properties: {
        component_id: 13,
        component_name: "Crosswalk",
        component_subtype: "Continental",
        moped_subcomponents: "",
        project_id: 156,
        project_description: "john's latest project",
        capitally_funded: false,
        completion_end_date: null,
        construction_start_date: null,
        current_phase: "",
        current_status: "active",
        date_added: "2021-01-07T23:21:38.359434+00:00",
        ecapris_subproject_id: 123456,
        end_date: null,
        fiscal_year: "2020",
        funding_source_name: null,
        is_deleted: false,
        milestone_id: null,
        project_designer: null,
        project_inspector: null,
        project_length: 87,
        project_name: "john's latest project",
        project_note: null,
        project_order: null,
        project_partner: null,
        project_sponsor: "None",
        project_team_members: null,
        status_id: 0,
        status_name: null,
        task_order_name: null,
        timeline_id: null,
        type_name: null,
        updated_at: "2022-03-01T23:37:23.289045+00:00",
      },
      geometry: {
        type: "MultiPoint",
        coordinates: [
          [-97.74816440418363, 30.273682205213518],
          [-97.74922471493483, 30.27396770463254],
          [-97.74847788736224, 30.272747956127176],
        ],
      },
    },
  ],
};
