export const returnAMDSignalInfrastructureMilestoneTemplate = (projectId) => {
  return [
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 36,
      milestone_order: 1,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 38,
      milestone_order: 2,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 39,
      milestone_order: 3,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 40,
      milestone_order: 4,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 41,
      milestone_order: 5,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 63,
      milestone_order: 6,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 43,
      milestone_order: 7,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 64,
      milestone_order: 8,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 44,
      milestone_order: 9,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 47,
      milestone_order: 10,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 50,
      milestone_order: 11,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 51,
      milestone_order: 12,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 53,
      milestone_order: 13,
    },
  ];
};

export const returnAMDInspectionOnlyMilestoneTemplate = (projectId) => {
  return [
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 63,
      milestone_order: 1,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 43,
      milestone_order: 2,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 64,
      milestone_order: 3,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 44,
      milestone_order: 4,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 47,
      milestone_order: 5,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 50,
      milestone_order: 6,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 51,
      milestone_order: 7,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 53,
      milestone_order: 8,
    },
  ];
};

export const returnPDDMilestoneTemplate = (projectId) => {
  return [
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 22,
      milestone_order: 1,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 59,
      milestone_order: 2,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 60,
      milestone_order: 3,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 1,
      milestone_order: 4,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 61,
      milestone_order: 5,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 9,
      milestone_order: 6,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 57,
      milestone_order: 7,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 58,
      milestone_order: 8,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 7,
      milestone_order: 9,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 8,
      milestone_order: 10,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 21,
      milestone_order: 11,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 19,
      milestone_order: 12,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 62,
      milestone_order: 13,
    },
    {
      project_id: projectId,
      is_deleted: false,
      completed: false,
      milestone_id: 4,
      milestone_order: 14,
    },
  ];
};


export const returnArterialManagementPhaseTemplate = projectId => {
  return [
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 1,
      subphase_id: null,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 2,
      subphase_id: 15,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 6,
      subphase_id: 17,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 6,
      subphase_id: 18,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 7,
      subphase_id: 3,
      phase_description: "Electric Service Planning Application (ESPA)",
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 7,
      subphase_id: 3,
      phase_description: "Traffic Control Plan (TCP) / Right of Way (ROW)",
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 8,
      subphase_id: null,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 9,
      subphase_id: 6,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 9,
      subphase_id: 7,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 9,
      subphase_id: 26,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 9,
      subphase_id: 27,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 10,
      subphase_id: null,
    },
    {
      project_id: projectId,
      is_deleted: false,
      phase_id: 11,
      subphase_id: null,
    },
  ];
};
