DELETE FROM moped_components WHERE component_name = 'Bike lane' AND component_subtype = 'Ramp to Sidewalk';
DELETE FROM moped_components WHERE component_name = 'Bike Lane' AND component_subtype = 'Advisory';
DELETE FROM moped_components WHERE component_name = 'Shared Street' AND component_subtype is null;
DELETE FROM moped_components WHERE component_name = 'Green Infrastructure' AND component_subtype = 'Rain Garden';
DELETE FROM moped_components WHERE component_name = 'Green Infrastructure' AND component_subtype = 'Vegetated Channel';
DELETE FROM moped_components WHERE component_name = 'Neighborhood Bikeway' AND component_subtype is null;
DELETE FROM moped_components WHERE component_name = 'Roadway' AND component_subtype is null;
DELETE FROM moped_components WHERE component_name = 'Pedestrian' AND component_subtype = 'Park and Walk';
DELETE FROM moped_components WHERE component_name = 'Pedestrian' AND component_subtype = 'Crossing Improvements';
DELETE FROM moped_components WHERE component_name = 'Pedestrian' AND component_subtype = 'Zone';
DELETE FROM moped_components WHERE component_name = 'Roadway' AND component_subtype = 'Shoulder';
DELETE FROM moped_components WHERE component_name = 'Signage' AND component_subtype = 'In-street Yield to Pedestrians';
DELETE FROM moped_components WHERE component_name = 'Roadway' AND component_subtype = 'Widening';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Bridge';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Curb Ramps';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Grade Separated Crossing';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Low Water Crossing';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Shared Use Path (Paved In-Street)';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Shared Use Path (Paved)';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Shared Use Path (Paved One-Way Bike)';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Tunnel';
DELETE FROM moped_components WHERE component_name = 'Trail' AND component_subtype = 'Unpaved';
DELETE FROM moped_components WHERE component_name = 'Sidewalk' AND component_subtype = 'Improvements';
