INSERT INTO moped_components (component_name, component_subtype, line_representation,feature_layer_id, status_id) VALUES
    ('Bike lane','Ramp to Sidewalk',TRUE,4, 1),
    ('Bike Lane','Advisory',TRUE,4, 1),
    ('Shared Street',null,TRUE,4, 1),
    ('Green Infrastructure','Rain Garden',FALSE,5, 1),
    ('Green Infrastructure','Vegetated Channel',FALSE,5, 1),
    ('Neighborhood Bikeway',null,TRUE,4, 1),
    ('Roadway',null,TRUE,4, 1),
    ('Pedestrian','Park and Walk',FALSE,5, 1),
    ('Pedestrian','Crossing Improvements',FALSE,5, 1),
    ('Pedestrian','Zone',TRUE,4, 1),
    ('Roadway','Shoulder',TRUE,4, 1),
    ('Signage','In-street Yield to Pedestrians',TRUE,4, 1),
    ('Roadway','Widening',TRUE,4, 1),
    ('Trail','Bridge',TRUE,4, 1),
    ('Trail','Curb Ramps',TRUE,4, 1),
    ('Trail','Grade Separated Crossing',TRUE,4, 1),
    ('Trail','Low Water Crossing',TRUE,4, 1),
    ('Trail','Shared Use Path (Paved In-Street)',TRUE,4, 1),
    ('Trail','Shared Use Path (Paved)',TRUE,4, 1),
    ('Trail','Shared Use Path (Paved One-Way Bike)',TRUE,4, 1),
    ('Trail','Tunnel',TRUE,4, 1),
    ('Trail','Unpaved',TRUE,4, 1),
    ('Sidewalk','Improvements',TRUE,4, 1);
