#!/usr/bin/env bash
#
# Hasura Cluster Tool(kit)
#   This is a tool kit that helps manage the MOPED cluster.
#
# Austin Transportation Department
# Data & Technology Services
#
set -o errexit

HIDE_HASURA_KIT_BANNER="FALSE"

#
# Pings the Hasura server, returns True if it is ready to accept connections.
#
function hasura_server_ready() {
  HASURA_SERVER_STATUS=$(curl --silent http://localhost:8080/v1/version)
  if [[ "${HASURA_SERVER_STATUS}" =~ "version" ]]; then
    echo "TRUE"
  else
    echo "FALSE"
  fi
}

#
# Checks the hasura server output (if any) and checks if it is ready,
# if not, it waits 1 second and tries again (up to 60 seconds)
#
function wait_server_ready() {
  INITIALIZATION_TIMEOUT_LIMIT=60
  INITIALIZATION_COUNT=1
  while [ "$(hasura_server_ready)" = "FALSE" ]; do
    echo "Hasura server not ready, please wait. ${INITIALIZATION_COUNT}/${INITIALIZATION_TIMEOUT_LIMIT}"
    if [ $INITIALIZATION_COUNT -gt $INITIALIZATION_TIMEOUT_LIMIT ]; then
      echo "Hasura server unavailable"
      exit 1
    fi
    sleep 1
    INITIALIZATION_COUNT=$(($INITIALIZATION_COUNT + 1))
  done
}

#
# Waits until the local hasura server is ready
#
function run_migration() {
  echo "Checking the Hasura server is ready...";
  wait_server_ready;
  echo "----- MIGRATIONS STARTED -----";
  echo "Applying migration";
  hasura migrate apply;
  echo "Applying metadata";
  hasura metadata apply;
  echo "Applying seeds";
  hasura seeds apply;
  echo "----- MIGRATIONS FINISHED -----";
}

#
# Starts the cluster and does NOT run migrations...
#
function start_only() {
  docker-compose -f docker-compose.yml up -d;
}

#
# Starts the cluster, runs the migrations automatically
#
function start() {
  start_only;
  run_migration;
  status;
}

#
# Changes the current environment
#
function setenv() {
  ENVIRONMENT=$1
  if [[ "${ENVIRONMENT}" != "production" ]] && [[ "${ENVIRONMENT}" != "staging" ]] && [[ "${ENVIRONMENT}" != "local" ]]; then
    echo "Invalid environment: '${ENVIRONMENT}' (command ignored)";
    exit 0;
  fi

  echo "Switched environment to ${ENVIRONMENT}";
  cat "./config/hasura.${ENVIRONMENT}.yaml" > ./config.yaml;
  echo "current_environment: ${ENVIRONMENT}" >./hasura.current_environment.yaml;
  cat ./hasura.current_environment.yaml
}

#
# Stops the cluster and removes any created volumes
#
function stop() {
  docker-compose -f docker-compose.yml down --volumes;
}

#
# Removes any volumes whose names start with the string "moped"
#
function prune() {
   docker volume rm $(docker volume ls --filter name=moped* -q);
}

#
# Attaches to the log output of all containers in the cluster
#
function follow() {
  docker-compose logs --follow
}

#
# Shows the status of the server (after being started)
#
function status() {
  VERSION=$(curl --silent http://localhost:8080/v1/version)
  STATUS=$(curl --silent http://localhost:8080/healthz)
  echo -e "\n------------------------------------------"
  echo "Hasura Server Status":
  echo "------------------------------------------"
  echo "Status: ${STATUS}"
  echo "Version: ${VERSION}"
  echo "You may run 'hasura console' now!"
  echo -e "------------------------------------------\n"
}

#
# Run the Hasura Console
#
function console() {
  echo "Starting the Hasura Console... (press Ctrl+C to stop)";
  hasura console;
}

#
# Shows a fancy banner
#
function show_hasura_kit_banner() {
  cat <<HASURA_EOM
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
██░██░█░▄▄▀█░▄▄█░██░█░▄▄▀█░▄▄▀████░▄▄▀█░██░██░█░▄▄█▄░▄█░▄▄█░▄▄▀████░█▀▄██▄██▄░▄██
██░▄▄░█░▀▀░█▄▄▀█░██░█░▀▀▄█░▀▀░████░████░██░██░█▄▄▀██░██░▄▄█░▀▀▄████░▄▀███░▄██░███
██░██░█▄██▄█▄▄▄██▄▄▄█▄█▄▄█▄██▄████░▀▀▄█▄▄██▄▄▄█▄▄▄██▄██▄▄▄█▄█▄▄████░██░█▄▄▄██▄███
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
HASURA_EOM
}

if [[ "${HIDE_HASURA_KIT_BANNER}" != "TRUE" ]]; then
  show_hasura_kit_banner
  echo -e "Copyright © 1985 Data & Tech Services Corp. \t\t Hasura Cluster: \e[32m $1 \e[0m"
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" && $1 $2 $3;
else

  echo "Hasura Cluster: $1" && $1 $2 $3;
fi
