table:
  name: feature_street_segments
  schema: public
insert_permissions:
  - role: moped-admin
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - component_id
        - ctn_segment_id
        - from_address_min
        - full_street_name
        - geography
        - is_deleted
        - line_type
        - source_layer
        - symbol
        - to_address_max
  - role: moped-editor
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - component_id
        - ctn_segment_id
        - from_address_min
        - full_street_name
        - geography
        - is_deleted
        - line_type
        - source_layer
        - symbol
        - to_address_max
select_permissions:
  - role: moped-admin
    permission:
      columns:
        - is_deleted
        - full_street_name
        - line_type
        - source_layer
        - component_id
        - created_by_user_id
        - ctn_segment_id
        - from_address_min
        - id
        - length_feet
        - symbol
        - to_address_max
        - updated_by_user_id
        - created_at
        - updated_at
        - geography
      filter: {}
      allow_aggregations: true
  - role: moped-editor
    permission:
      columns:
        - is_deleted
        - full_street_name
        - line_type
        - source_layer
        - component_id
        - created_by_user_id
        - ctn_segment_id
        - from_address_min
        - id
        - length_feet
        - symbol
        - to_address_max
        - updated_by_user_id
        - created_at
        - updated_at
        - geography
      filter: {}
      allow_aggregations: true
  - role: moped-viewer
    permission:
      columns:
        - is_deleted
        - full_street_name
        - line_type
        - source_layer
        - component_id
        - created_by_user_id
        - ctn_segment_id
        - from_address_min
        - id
        - length_feet
        - symbol
        - to_address_max
        - updated_by_user_id
        - created_at
        - updated_at
        - geography
      filter: {}
      allow_aggregations: true
update_permissions:
  - role: moped-admin
    permission:
      columns:
        - component_id
        - ctn_segment_id
        - from_address_min
        - full_street_name
        - geography
        - is_deleted
        - line_type
        - source_layer
        - symbol
        - to_address_max
      filter: {}
      check: {}
      set:
        updated_by_user_id: x-hasura-user-db-id
  - role: moped-editor
    permission:
      columns:
        - component_id
        - ctn_segment_id
        - from_address_min
        - full_street_name
        - geography
        - is_deleted
        - line_type
        - source_layer
        - symbol
        - to_address_max
      filter: {}
      check: {}
      set:
        updated_by_user_id: x-hasura-user-db-id
event_triggers:
  - name: activity_log_feature_street_segments
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_ENDPOINT
    headers:
      - name: x-hasura-admin-secret
        value_from_env: ACTIVITY_LOG_API_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "query": "mutation InsertActivity($object: moped_activity_log_insert_input!) { insert_moped_activity_log_one(object: $object) { activity_id } }",
            "variables": {
              "object": {
                "record_id": {{ $body.event.data.new.id }},
                "record_type":  {{ $body.table.name }},
                "activity_id": {{ $body.id }},
                "record_data": {"event": {{ $body.event }}},
                "description": [{"newSchema": "true"}],
                "operation_type": {{ $body.event.op }},
                "updated_by_user_id": {{ $session_variables?['x-hasura-user-db-id'] ?? 1}}
              }
            }
          }
      method: POST
      query_params: {}
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
