table:
  name: moped_proj_personnel
  schema: public
object_relationships:
  - name: moped_user
    using:
      foreign_key_constraint_on: user_id
  - name: project
    using:
      foreign_key_constraint_on: project_id
array_relationships:
  - name: moped_proj_personnel_roles
    using:
      foreign_key_constraint_on:
        column: project_personnel_id
        table:
          name: moped_proj_personnel_roles
          schema: public
insert_permissions:
  - role: moped-admin
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - is_deleted
        - notes
        - project_id
        - user_id
  - role: moped-editor
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - is_deleted
        - notes
        - project_id
        - user_id
select_permissions:
  - role: moped-admin
    permission:
      columns:
        - created_at
        - created_by_user_id
        - is_deleted
        - notes
        - project_id
        - project_personnel_id
        - updated_at
        - updated_by_user_id
        - user_id
      filter: {}
  - role: moped-editor
    permission:
      columns:
        - created_at
        - created_by_user_id
        - is_deleted
        - notes
        - project_id
        - project_personnel_id
        - updated_at
        - updated_by_user_id
        - user_id
      filter: {}
  - role: moped-viewer
    permission:
      columns:
        - created_at
        - created_by_user_id
        - is_deleted
        - notes
        - project_id
        - project_personnel_id
        - updated_at
        - updated_by_user_id
        - user_id
      filter: {}
update_permissions:
  - role: moped-admin
    permission:
      columns:
        - is_deleted
        - notes
        - project_id
        - user_id
      filter: {}
      check: null
      set:
        updated_by_user_id: x-hasura-user-db-id
  - role: moped-editor
    permission:
      columns:
        - is_deleted
        - notes
        - project_id
        - user_id
      filter: {}
      check: null
      set:
        updated_by_user_id: x-hasura-user-db-id
event_triggers:
  - name: activity_log_moped_proj_personnel
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_ENDPOINT
    headers:
      - name: x-hasura-admin-secret
        value_from_env: ACTIVITY_LOG_API_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "query": "mutation InsertActivity($object: moped_activity_log_insert_input!) { insert_moped_activity_log_one(object: $object) { activity_id } }",
            "variables": {
              "object": {
                "record_id": {{ $body.event.data.new.project_personnel_id }},
                "record_type":  {{ $body.table.name }},
                "activity_id": {{ $body.id }},
                "record_project_id": {{ $body.event.data.new.project_id }},
                "record_data": { "event": {{ $body.event }}},
                "description": [{"newSchema": "true"}],
                "operation_type": {{ $body.event.op }},
                "updated_by_user_id": {{ $session_variables?['x-hasura-user-db-id'] ?? 1}}
              }
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
