table:
  name: moped_proj_funding
  schema: public
object_relationships:
  - name: moped_fund_program
    using:
      foreign_key_constraint_on: funding_program_id
  - name: moped_fund_source
    using:
      foreign_key_constraint_on: funding_source_id
insert_permissions:
  - role: moped-admin
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - dept_unit
        - fdu
        - fund
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - project_id
    comment: No insert permissions on audit fields
  - role: moped-editor
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - dept_unit
        - fdu
        - fund
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - project_id
    comment: No insert permissions on audit fields
select_permissions:
  - role: moped-admin
    permission:
      columns:
        - created_at
        - created_by_user_id
        - dept_unit
        - ecapris_funding_id
        - fdu
        - fund
        - fund_dept_unit
        - fund_name
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - is_editable
        - is_legacy_funding_record
        - proj_funding_id
        - project_id
        - updated_at
        - updated_by_user_id
      filter: {}
      allow_aggregations: true
  - role: moped-editor
    permission:
      columns:
        - created_at
        - created_by_user_id
        - dept_unit
        - ecapris_funding_id
        - fdu
        - fund
        - fund_dept_unit
        - fund_name
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - is_editable
        - is_legacy_funding_record
        - proj_funding_id
        - project_id
        - updated_at
        - updated_by_user_id
      filter: {}
      allow_aggregations: true
  - role: moped-viewer
    permission:
      columns:
        - created_at
        - created_by_user_id
        - dept_unit
        - ecapris_funding_id
        - fdu
        - fund
        - fund_dept_unit
        - fund_name
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - is_editable
        - is_legacy_funding_record
        - proj_funding_id
        - project_id
        - updated_at
        - updated_by_user_id
      filter: {}
      allow_aggregations: true
update_permissions:
  - role: moped-admin
    permission:
      columns:
        - dept_unit
        - fdu
        - fund
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - project_id
      filter: {}
      check: null
      set:
        updated_by_user_id: x-hasura-user-db-id
    comment: No update permissions on audit fields
  - role: moped-editor
    permission:
      columns:
        - dept_unit
        - fdu
        - fund
        - funding_amount
        - funding_description
        - funding_program_id
        - funding_source_id
        - funding_status_id
        - is_deleted
        - project_id
      filter: {}
      check: null
      set:
        updated_by_user_id: x-hasura-user-db-id
    comment: No update permissions on audit fields
event_triggers:
  - name: activity_log_moped_proj_funding
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_ENDPOINT
    headers:
      - name: x-hasura-admin-secret
        value_from_env: ACTIVITY_LOG_API_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "query": "mutation InsertActivity( $object: moped_activity_log_insert_input!) { insert_moped_activity_log_one(object: $object) { activity_id } }",
            "variables": {
                "object": {
                    "record_id": {{ $body.event.data.new.proj_funding_id }},
                    "record_type":  {{ $body.table.name }},
                    "activity_id": {{ $body.id }},
                    "record_project_id": {{ $body.event.data.new.project_id }},
                    "record_data": {"event": {{ $body.event }}},
                    "description": [{"newSchema": "true"}],
                    "operation_type": {{ $body.event.op }},
                    "updated_by_user_id": {{ $session_variables?['x-hasura-user-db-id'] ?? 1}}
                }
              }
            }
      method: POST
      query_params: {}
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
