table:
  name: moped_proj_components
  schema: public
object_relationships:
  - name: moped_components
    using:
      foreign_key_constraint_on: component_id
  - name: moped_phase
    using:
      foreign_key_constraint_on: phase_id
  - name: moped_subphase
    using:
      foreign_key_constraint_on: subphase_id
array_relationships:
  - name: feature_drawn_lines
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_drawn_lines
          schema: public
  - name: feature_drawn_points
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_drawn_points
          schema: public
  - name: feature_intersections
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_intersections
          schema: public
  - name: feature_school_beacons
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_school_beacons
          schema: public
  - name: feature_signals
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_signals
          schema: public
  - name: feature_street_segments
    using:
      manual_configuration:
        column_mapping:
          project_component_id: component_id
        insertion_order: null
        remote_table:
          name: feature_street_segments
          schema: public
  - name: moped_proj_component_tags
    using:
      foreign_key_constraint_on:
        column: project_component_id
        table:
          name: moped_proj_component_tags
          schema: public
  - name: moped_proj_component_work_types
    using:
      foreign_key_constraint_on:
        column: project_component_id
        table:
          name: moped_proj_component_work_types
          schema: public
  - name: moped_proj_components_subcomponents
    using:
      foreign_key_constraint_on:
        column: project_component_id
        table:
          name: moped_proj_components_subcomponents
          schema: public
insert_permissions:
  - role: moped-admin
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
  - role: moped-editor
    permission:
      check: {}
      set:
        created_by_user_id: x-hasura-user-db-id
        updated_by_user_id: x-hasura-user-db-id
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
select_permissions:
  - role: moped-admin
    permission:
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_component_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
      filter: {}
  - role: moped-editor
    permission:
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_component_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
      filter: {}
  - role: moped-viewer
    permission:
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_component_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
      filter: {}
update_permissions:
  - role: moped-admin
    permission:
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
      filter: {}
      check: {}
      set:
        updated_by_user_id: x-hasura-user-db-id
  - role: moped-editor
    permission:
      columns:
        - component_id
        - created_by_user_id
        - interim_project_component_id
        - phase_id
        - project_id
        - subphase_id
        - updated_by_user_id
        - description
        - location_description
        - completion_date
        - created_at
        - updated_at
        - is_deleted
        - srts_id
      filter: {}
      check: {}
      set:
        updated_by_user_id: x-hasura-user-db-id
event_triggers:
  - name: activity_log_moped_proj_components
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - interim_project_component_id
          - project_component_id
          - location_description
          - component_id
          - is_deleted
          - phase_id
          - completion_date
          - project_id
          - created_at
          - subphase_id
          - created_by_user_id
          - description
          - srts_id
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_ENDPOINT
    headers:
      - name: x-hasura-admin-secret
        value_from_env: ACTIVITY_LOG_API_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "query": "mutation InsertActivity($object: moped_activity_log_insert_input!) { insert_moped_activity_log_one(object: $object) { activity_id }}",
            "variables": {
              "object": {
                "record_id": {{ $body.event.data.new.project_component_id }},
                "record_type":  {{ $body.table.name }},
                "activity_id": {{ $body.id }},
                "record_project_id": {{ $body.event.data.new.project_id }},
                "record_data": {"event": {{ $body.event }}},
                "description": [{"newSchema": "true"}],
                "operation_type": {{ $body.event.op }},
                "updated_by_user_id": {{ $session_variables?['x-hasura-user-db-id'] ?? 1}}
              }
            }
          }
      method: POST
      query_params: {}
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: activity_log_moped_proj_components_update
    definition:
      enable_manual: false
      update:
        columns:
          - project_id
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_ENDPOINT
    headers:
      - name: x-hasura-admin-secret
        value_from_env: ACTIVITY_LOG_API_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "query": "mutation InsertActivity($object: moped_activity_log_insert_input!) { insert_moped_activity_log_one(object: $object) { activity_id } }",
            "variables": {
              "object": {
                "record_id": {{ $body.event.data.new.project_component_id }},
                "record_type":  {{ $body.table.name }},
                "activity_id": {{ $body.id }},
                "record_project_id": {{ $body.event.data.old.project_id }},
                "record_data": {"event": {{ $body.event }}},
                "description": [{"newSchema": "true"}],
                "operation_type": {{ $body.event.op }},
                "updated_by_user_id": {{ $session_variables?['x-hasura-user-db-id'] ?? 1}}
              },
            }
          }
      method: POST
      query_params: {}
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
