# This file contains example HTTP calls and it it also the configuration
# file for the VSCode plugin "REST Client" https://open-vsx.org/extension/humao/rest-client. 

# Add the following into the .vscode/settings.json file to use the environment 
# variables in this file:

# {
#     "rest-client.environmentVariables": {
#         "$shared": {
#             "API_SERVER": "loaclhost",
#             "{{AUTH_BEARER_TOKEN}}": <Token>
#         },
#     }
# }

# TODO, move some of this config into a readme or something

# Health Check
{{API_SERVER}}

### Auth Health Check
{{API_SERVER}}/auth/
### auth_current_user()

# Current User. You can get the AUTH_BEARER_TOKEN from the browser's console by looking at 
# a request to graphql-engine. It is only as long-lived as your browser session.
{{API_SERVER}}/auth/current_user
Authorization: Bearer {{AUTH_BEARER_TOKEN}}

### auth_current_user2()
{{API_SERVER}}/auth/current_user2
Authorization: Bearer {{AUTH_BEARER_TOKEN}}

### Users listing
{{API_SERVER}}/users
Authorization: Bearer {{AUTH_BEARER_TOKEN}}

### user_get_user()
# The USER_ID is the "Username" key from the previous request 👆
{{API_SERVER}}/users/{{USER_ID}}
Authorization: Bearer {{AUTH_BEARER_TOKEN}}
