ALTER TABLE moped_project
    DROP COLUMN project_uuid,
    DROP COLUMN project_description_public,
    DROP COLUMN project_importance,
    DROP COLUMN project_order,
    DROP COLUMN timeline_id,
    DROP COLUMN end_date,
    DROP COLUMN project_length,
    DROP COLUMN fiscal_year,
    DROP COLUMN project_priority,
    DROP COLUMN milestone_id,
    DROP COLUMN work_assignment_id;
