const COMPONENTS_MAP = [
  { in: "_Project Limits", out: 0 },
  { in: "_TBD", out: 0 },
  { in: "Access Control - Driveway Closure", out: 1 },
  { in: "Access Control - Driveway Modification", out: 2 },
  { in: "Access Control - Hardened Centerline", out: 3 },
  { in: "Access Control - Median - Modification", out: 4 },
  { in: "Access Control - Median - New", out: 4 },
  { in: "Bike Box", out: 5 },
  { in: "Bike Lane", out: 6 },
  { in: "Bike Lane - Buffered", out: 7 },
  { in: "Bike Lane - Climbing", out: 8 },
  { in: "Bike Lane - Colored", out: 9 },
  { in: "Bike Lane - Contraflow", out: 10 },
  { in: "Bike Lane - Protected One-Way", out: 11 },
  { in: "Bike Lane - Protected Two-Way", out: 12 },
  { in: "Bike Lane - Removed", out: 0 },
  { in: "Bike Lane - Suggested", out: 68 },
  { in: "Bike Lane - wParking", out: 15 },
  { in: "Bike Parking", out: 19 },
  { in: "Bike Parking Corral", out: 20 },
  { in: "Bike Ramp to Sidewalk", out: 67 },
  { in: "Bike Turn Lane", out: 21 },
  { in: "Bike Wide Curb Lane", out: 22 },
  { in: "Crossbike - Pavement Markings", out: 23 },
  { in: "Crosswalk - Continental", out: 13 },
  { in: "Crosswalk - Creative", out: 14 },
  { in: "Crosswalk - Raised", out: 15 },
  { in: "Crosswalk - Remove", out: 0 },
  { in: "Driveway Gate", out: 24 },
  { in: "Dynamic Speed Display Device", out: 25 },
  { in: "Guardrail", out: 26 },
  { in: "Healthy Street", out: 69 },
  { in: "Highway - Access Ramp", out: 27 },
  { in: "Highway - Added Capacity / Lanes", out: 28 },
  { in: "Highway - Collector Distributor", out: 29 },
  { in: "Highway - Flyover", out: 30 },
  { in: "Highway - Intersection Grade Seperation", out: 31 },
  { in: "Highway - Managed Lane", out: 32 },
  { in: "Highway - Toll Road", out: 33 },
  { in: "Intersection - Roundabout", out: 64 },
  { in: "Intersection Improvement", out: 66 },
  { in: "Landscaping", out: 34 },
  { in: "Lighting (Street or Trail Illumination)", out: 60 },
  { in: "Miscellaneous", out: 0 },
  { in: "Neighborhood Bikeway (BBlvd)", out: 72 },
  { in: "New Bridge (all modes)", out: 0 },
  { in: "New Connection - Street", out: 73 },
  { in: "New Connection - Trail", out: 85 },
  { in: "New Connection - Trail or Street", out: 85 },
  { in: "Park and Walk", out: 74 },
  { in: "Pedestrian Crossing Improvements", out: 75 },
  { in: "Pedestrian Zone", out: 76 },
  { in: "Placemaking", out: 35 },
  { in: "Plan - Corridor", out: 0 },
  { in: "Plan - School", out: 0 },
  { in: "Plan - Small Area", out: 0 },
  { in: "Rail Crossing Improvement", out: 0 },
  { in: "Rain Garden", out: 70 },
  { in: "Refuge Island - Bike", out: 36 },
  { in: "Refuge Island - BikePed", out: 38 },
  { in: "Refuge Island - Ped", out: 37 },
  { in: "Remove DY", out: 0 },
  { in: "Road Closed", out: null },
  { in: "Roadway - Added Capacity / Lanes", out: null },
  { in: "School Zone - Conduct Study", out: null },
  { in: "School Zone - Flasher", out: 39 },
  { in: "School Zone - Pavement Markings", out: 40 },
  { in: "Sharrows", out: 57 },
  { in: "Sharrows - Wide Curb Lane", out: 58 },
  { in: "Shoulder", out: 77 },
  { in: "Sidewalk", out: 41 },
  { in: "Sidewalk - Fix Obstructions", out: 89 },
  { in: "Sidewalk - In Street", out: 42 },
  { in: "Sidewalk - Repair", out: null },
  { in: "Sidewalk - Wide", out: 43 },
  { in: "Sidewalk - With Curb and Gutter", out: 44 },
  { in: "Sidewalk Ramps", out: 45 },
  { in: "Signage", out: 59 },
  { in: "Signage - In-street Yield to Peds", out: 78 },
  { in: "Signage - Pedestrian Sign with Activated Flasher", out: 63 },
  { in: "Signal - PHB", out: 16 },
  { in: "Signal - RRFB", out: 63 },
  { in: "Signal - Traffic", out: 18 },
  { in: "Speed Management - Chicane", out: 46 },
  { in: "Speed Management - Neigh.Traffic Circle", out: 47 },
  { in: "Speed Management - Speed Cushions (Asphalt)", out: 48 },
  {
    in: "Speed Management - Speed Cushions (Asphalt) Device Location",
    out: 48,
  },
  { in: "Speed Management - Speed Cushions (Rubber)", out: 49 },
  { in: "Speed Management - Speed Cushions (Rubber) Device Location", out: 49 },
  { in: "Speed Management - Speed Humps", out: 50 },
  { in: "Speed Management - Speed Humps Device Location", out: 50 },
  { in: "Stop Bar Pavement Marking", out: 51 },
  { in: "Street Widening", out: 79 },
  { in: "Study - Misc", out: 0 },
  { in: "Temp Traffic Control", out: 0 },
  { in: "Trail - Bridge", out: 80 },
  { in: "Trail - Curb Ramps", out: 81 },
  { in: "Trail - Grade Separated Crossing", out: 82 },
  { in: "Trail - Low Water Crossing", out: 83 },
  { in: "Trail - Maintenance", out: 85 },
  { in: "Trail - Shared Use Path (paved in street)", out: 84 },
  { in: "Trail - Shared Use Path (paved)", out: 85 },
  { in: "Trail - Shared Use Path (paved one-way bike)", out: 86 },
  { in: "Trail - Tunnel", out: 87 },
  { in: "Trail - Unpaved", out: 88 },
  { in: "Trail - Urban Trail (paved)", out: 85 },
  { in: "Trail - Urban Trail (paved dual trail)", out: null },
  { in: "Transit - BRT", out: null },
  { in: "Transit - Bus Stop - Consolidation", out: 62 },
  { in: "Transit - Bus Stop - Enhanced", out: 62 },
  { in: "Transit - Bus Stop - Modification", out: 62 },
  { in: "Transit Lane", out: 52 },
  { in: "Transit Managed Lane Access Point", out: 53 },
  { in: "Transit Queue Jump", out: 54 },
  { in: "Transit/Bike Lane", out: 55 },
  { in: "Trim Vegetation", out: 89 },
  { in: "Two-stage Turn Queue", out: 56 },
  { in: "Vegetated Channel", out: 71 },
];

const COMPONENT_WORK_TYPES_MAP = [
  { in: "Construction Inspection", out: null },
  { in: "Const / Curb Mod / Widening", out: 2 },
  { in: "Design Review", out: null },
  { in: "Lane Conv", out: 4 },
  { in: "Maintenance/Repair", out: 5 },
  { in: "Modification", out: 6 },
  { in: "New", out: 7 },
  { in: "Other", out: null },
  { in: "Parking Mod", out: 8 },
  { in: "Reinstall", out: 9 },
  { in: "Remove BL (spell out BL as Bike Lane)", out: 10 },
  { in: "Remove DY (spell out DY as Double Yellow)", out: 11 },
  { in: "Replacement", out: 12 },
  { in: "Signal Take Over", out: 13 },
  { in: "Bicycle Lane Protection - New", out: 7 },
  { in: "Bicycle Lane Protection - Upgrade", out: 6 },
  
  { in: "Pedestrian", out: null },
  { in: "Markings / Signage Only", out: null },
  { in: "RTurn Only - BL Fix", out: null },
  { in: "Temp Closure", out: null },
  { in: "Feasibility Study", out: null },
  { in: "Neighborhood Bikeway (BBlvd)", out: null },
  { in: "Neighborhood Bikeway (BBlvd) - Existing TCalming", out: null },
  { in: "TBD", out: null },
  { in: "Road Closed", out: null },
];

module.exports = {
  COMPONENTS_MAP,
  COMPONENT_WORK_TYPES_MAP,
};
