const ENTITIES_MAP = [
  { in: "COA_TPW", out: 1 },
  { in: "COA_TPW_ActiveTrans", out: 2 },
  { in: "COA_TPW_AMD", out: 3 },
  { in: "COA_TPW_AMD_DataCollection", out: null },
  { in: "COA_TPW_DevReview", out: 4 },
  { in: "COA_TPW_PedCrossing", out: null },
  { in: "COA_TPW_ROW", out: 5 },
  { in: "COA_TPW_SMD", out: 6 },
  { in: "COA_TPW_TED_PDD", out: 7 },
  { in: "COA_TPW_TED", out: 8 },
  { in: "COA_TPW_TED_LATM", out: null },
  { in: "COA_TPW_TED_PPD", out: 10 },
  { in: "COA_TPW_TED_Safety", out: null },
  { in: "COA_TPW_TED_SpeedMmgt", out: 9 },
  { in: "COA_TPW_TED_TransitEP", out: 13 },
  { in: "CapitalMetro", out: 26 },
  { in: "COA_Aviation", out: 14 },
  { in: "COA_CorridorProg", out: 15 },
  { in: "COA_DSD", out: 16 },
  { in: "COA_EDD", out: 17 },
  { in: "COA_PARD", out: 18 },
  { in: "COA_PAZ", out: 19 },
  { in: "COA_PWD", out: 20 },
  { in: "COA_TPW_NPP", out: 21 },
  { in: "COA_TPW_SidewalkSPD", out: 22 },
  { in: "COA_TPW_SRTS", out: 23 },
  { in: "COA_TPW_UrbanTrails", out: 24 },
  { in: "COA_WSPD", out: 25 },
  { in: "Consultant_Civilitude", out: null },
  { in: "Consultant_MWM", out: null },
  { in: "Consultant_RPS", out: null },
  { in: "CTRMA", out: 27 },
  { in: "PrivateDev", out: 33 },
  { in: "PrivatePartner_HillCountryConcervancy", out: 35 },
  { in: "PrivatePartner_MuellerFoundation", out: 36 },
  { in: "StateofTexas", out: 28 },
  { in: "SunsetValley", out: 29 },
  { in: "TravisCounty", out: 30 },
  { in: "TxDOT", out: 31 },
  { in: "WilliamsonCounty", out: 32 },
];

exports.ENTITIES_MAP = ENTITIES_MAP;
