const PARTNERS_MAP = [
  { in: "ATD_ActiveTrans", out: 2 },
  { in: "ATD_ActiveTrans.", out: 2 },
  { in: "ATD_AMD", out: 3 },
  { in: "ATD_SMD", out: 6 },
  { in: "ATD_SMD_CMTA", out: 6 },
  { in: "CapMetro", out: 26 },
  { in: "CMTA", out: 26 },
  { in: "CPO", out: 15 },
  { in: "PWD", out: 20 },
  { in: "ROW", out: 5 },
  { in: "SRTS", out: 23 },
  { in: "TxDOT", out: 31 },
  { in: "TXDOT", out: 31 },
  { in: "Urban Trails", out: 24 },
  { in: "ActiveTrans", out: 2 },
  { in: "ATD", out: 1 },
  { in: "ATD CapMetro", out: 26 },
  { in: "ATD_ActiveTrans", out: 2 },
  { in: "ATD_AMD_ATSD", out: 3 },
  { in: "ATD_ATSD", out: 2 },
  { in: "ATD_Sigals", out: 3 },
  { in: "CapMetro", out: 26 },
  { in: "PARD", out: 18 },
  { in: "PWD", out: 20 },
  { in: "Sidewalk", out: 22 },
  { in: "SRTS", out: 23 },
  { in: "SRTS_TBD", out: 23 },
  { in: "StreetAndBridge", out: 20 },
  { in: "Transportation Engineering Division", out: 8 },
  { in: "TXDOT", out: 31 },
  { in: "Urban Trails", out: 24 },
  { in: "UrbanTrails", out: 24 },
];

exports.PARTNERS_MAP = PARTNERS_MAP;
