// see https://docs.google.com/spreadsheets/d/1mRvElKNrswuWKga_I1iHSD4-5J9m4UsOuB8n5oyGvDs/edit#gid=1846025869
const SUBCOMPONENTS_MAP = [
  { in: "Continuous Flow Intersection", out: 6 },
  { in: "Curb Extension", out: 7 },
  { in: "Detection - Bicycle", out: 8 },
  { in: "Lane Changes", out: 9 },
  { in: "Protected Intersection Full", out: 10 },
  { in: "Protected Intersection Full (Shared Use)", out: 11 },
  { in: "Protected Intersection Partial", out: 12 },
  { in: "Radius Tightening", out: 13 },
  { in: "Slip Lane Removal", out: 14 },
  { in: "Smart Right", out: 15 },
  { in: "Square-up", out: 16 },
  { in: "Transit Corner Modification", out: 17 },
  { in: "Accessible Pedestrian Signal (APS)", out: 1 },
  { in: "Bicycle Accommodations at PHB", out: 18 },
  { in: "Bicycle Signal (Standard Signal + Bicycle Signal Sign)", out: 19 },
  { in: "Bicycle Signal Face (Experiment)", out: 20 },
  { in: "Bicycle Signal Face (InterimApp)", out: 21 },
  { in: "Detection - Vehicle", out: 22 },
  { in: "Leading Bicycle Interval", out: 23 },
  { in: "Leading Pedestrian Interval", out: 3 },
  { in: "Pedestrian Signal Head and Pushbuttons", out: 24 },
  { in: "Relocate Pedestrian Signal Pushbuttons", out: 24 },
  { in: "Protected Left Turn Phase", out: 25 },
  { in: "Timing Adjustment", out: 37 },
  { in: "Timing adjustment", out: 37 },
  { in: "Bus Stop Modification", out: 36 },
  { in: "Bus Stop Maintenance", out: 35 },
  { in: "Bus Stop Consolidation", out: 34 },
  { in: "Station Design - With SUP in Front", out: 33 },
  { in: "Station Design - With SUP Behind", out: 32 },
  { in: "Station Design - Step-out with Shared Landing", out: 31 },
  { in: "Station Design - Shared with Bike Lane in Front", out: 30 },
  { in: "Station Design - Island with Bike Lane Behind", out: 29 },
  { in: "Station Design - Floating with Bike Lane", out: 28 },
  { in: "Station Design - Curbside with Bike Lane Bypass", out: 27 },
  { in: "Bikeway Direction - Two-way", out: 26 },
];

const PROTECTION_SUBCOMPONENTS_MAP = [
  { in: "Car Free", out: 38 },
  { in: "Concrete", out: 39 },
  { in: "Concrete and On-Street Parking", out: 40 },
  { in: "Concrete Traffic Bump", out: 41 },
  { in: "Concrete with Landscape", out: 42 },
  { in: "Flex Posts", out: 43 },
  { in: "Flex Posts (City Post)", out: 44 },
  { in: "Flex Posts with Curb Stops", out: 45 },
  { in: "Flex Posts with On-Street Parking", out: 46 },
  { in: "Planters", out: 47 },
  { in: "Raised & Behind Curb", out: 48 },
];

module.exports = {
  SUBCOMPONENTS_MAP,
  PROTECTION_SUBCOMPONENTS_MAP,
};
