INSERT INTO moped_tags (name, type, slug, is_deleted) VALUES
    ('FHWA Experimentation', 'Other', 'fhwa_experimentation', TRUE),
    ('Bikeways - Partner Project Priorities', 'Other', 'bikeways_partner_project_priorities', FALSE),
    ('Bikeways - TXDOT High Priority', 'Other', 'bikeways_txdot_high_priority', FALSE),
    ('Bikeways - TXDOT Medium Priority', 'Other', 'bikeways_txdot_medium_priority', FALSE),
    ('Bikeways - TXDOT Missed Opportunities', 'Other', 'bikeways_txdot_missed_opportunities', FALSE),
    ('Bikeways - TXDOT Success', 'Other', 'bikeways_txdot_success', FALSE),
    ('Bikeways - Urban Trail CTRMA Priority Connections', 'Other', 'bikeways_urban_trail_ctrma_priority_connections', TRUE),
    ('Bikeways - Urban Trail Partner Projects', 'Other', 'bikeways_urban_trail_partner_projects', FALSE),
    ('Bikeways - Urban Trail Priority Connections', 'Other', 'bikeways_urban_trail_priority_connections', FALSE),
    ('Bikeways - Buffered to Protected', 'Other', 'bikeways_buffered_to_protected', FALSE),
    ('Bikeways Projects 2015', 'Work Plan', 'bikeways_projects_2015', TRUE),
    ('Bikeways Projects 2016', 'Work Plan', 'bikeways_projects_2016', TRUE),
    ('Bikeways Projects 2016 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2016_street_resurfacing', TRUE),
    ('Bikeways Projects 2017', 'Work Plan', 'bikeways_projects_2017', TRUE),
    ('Bikeways Projects 2017 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2017_street_resurfacing', TRUE),
    ('Bikeways Projects 2018', 'Work Plan', 'bikeways_projects_2018', TRUE),
    ('Bikeways Projects 2018 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2018_street_resurfacing', TRUE),
    ('Bikeways Projects 2019', 'Work Plan', 'bikeways_projects_2019', TRUE),
    ('Bikeways Projects 2019 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2019_street_resurfacing', TRUE),
    ('Bikeways Projects 2020 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2020_street_resurfacing', FALSE),
    ('Bikeways Projects 2021 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2021_street_resurfacing', FALSE),
    ('Bikeways Projects 2022 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2022_street_resurfacing', FALSE),
    ('Bikeways Projects 2023 - Street Resurfacing', 'Work Plan', 'bikeways_projects_2023_street_resurfacing', FALSE),
    ('Bikeways Construction Needs', 'Other', 'bikeways_construction_needs', FALSE),
    ('MAP Bikeways 2018 (LMAP)', 'Work Plan', 'map_bikeways_2018_lmap', FALSE),
    ('MAP Bikeways 2019', 'Work Plan', 'map_bikeways_2019', FALSE),
    ('MAP Bikeways 2020', 'Work Plan', 'map_bikeways_2020', FALSE),
    ('MAP Bikeways 2021', 'Work Plan', 'map_bikeways_2021', FALSE),
    ('MAP Bikeways 2022', 'Work Plan', 'map_bikeways_2022', FALSE),
    ('MAP Bikeways 2023', 'Work Plan', 'map_bikeways_2023', FALSE),
    ('MAP Coordination Projects', 'Other', 'map_coordination_projects', FALSE),
    ('MAP SRTS 2018 (LMAP)', 'Work Plan', 'map_srts_2018_lmap', FALSE),
    ('Project Connect - Initial Phase', 'Other', 'project_connect_initial_phase', FALSE),
    ('MAP SRTS 2018 - Early Out Projects', 'Work Plan', 'map_srts_2018_early_out_projects', TRUE),
    ('SRTS Unfunded', 'Other', 'srts_unfunded', FALSE);
