INSERT INTO moped_tags (name, type, slug, is_deleted) VALUES
('MAP Signals', 'Work Plan', 'map_signals', FALSE),
('MAP SRTS', 'Work Plan', 'map_srts', FALSE),
('MAP Transit Enhancement', 'Work Plan', 'map_transit_enhancement', FALSE),
('MAP Transit Speed and Reliability (CapMetro ILA)', 'Work Plan', 'map_transit_speed_reliability', FALSE),
('MAP Vision Zero - Major Safety', 'Work Plan', 'map_vision_zero_major_safety', FALSE),
('MAP Vision Zero - Ped Safety', 'Work Plan', 'map_vision_zero_ped_safety', FALSE),
('MAP Vision Zero - Rapid Response/Small Scale', 'Work Plan', 'map_vision_zero_rapid_response_small_scale', FALSE),
('MAP Vision Zero - Speed Management', 'Work Plan', 'map_vision_zero_speed_management', FALSE),
('MAP Vision Zero - Street Lighting', 'Work Plan', 'map_vision_zero_street_lighting', FALSE),
('MAP Vision Zero - Systemic Safety', 'Work Plan', 'map_vision_zero_systemic_safety', FALSE),
('MAP Vision Zero - Systemic Safety Curves', 'Work Plan', 'map_vision_zero_systemic_safety_curves', FALSE),
('MAP Bikeways 2024', 'Work Plan', 'map_bikeways_2024', FALSE),
('MAP Bikeways 2025', 'Work Plan', 'map_bikeways_2025', FALSE),
('MAP Signals 2025', 'Work Plan', 'map_signals_2025', FALSE),
('MAP SRTS 2025', 'Work Plan', 'map_srts_2025', FALSE),
('MAP Transit Enhancement 2025', 'Work Plan', 'map_transit_enhancement_2025', FALSE),
('MAP Transit Speed and Reliability (CapMetro ILA) 2025', 'Work Plan', 'map_transit_speed_reliability_2025', FALSE),
('MAP Vision Zero - Major Safety 2025', 'Work Plan', 'map_vision_zero_major_safety_2025', FALSE),
('MAP Vision Zero - Ped Safety 2025', 'Work Plan', 'map_vision_zero_ped_safety_2025', FALSE),
('MAP Vision Zero - Rapid Response/Small Scale 2025', 'Work Plan', 'map_vision_zero_rapid_response_small_scale_2025', FALSE),
('MAP Vision Zero - Speed Management 2025', 'Work Plan', 'map_vision_zero_speed_management_2025', FALSE),
('MAP Vision Zero - Street Lighting 2025', 'Work Plan', 'map_vision_zero_street_lighting_2025', FALSE),
('MAP Vision Zero - Systemic Safety 2025', 'Work Plan', 'map_vision_zero_systemic_safety_2025', FALSE),
('MAP Vision Zero - Systemic Safety Curves 2025', 'Work Plan', 'map_vision_zero_systemic_safety_curves_2025', FALSE);
