#
# Builds Cognito Triggers for Moped Authentication
#
name: "Build & Publish Moped API"

on:
  push:
    branches:
      - main
      - production
    paths:
      - ".github/workflows/atd_moped_api.yml"
      - ".github/workflows/aws-moped-api-helper.sh"
      - "moped-api/**"
  pull_request:
    paths:
      - ".github/workflows/atd_moped_api.yml"
      - ".github/workflows/aws-moped-api-helper.sh"
      - "moped-api/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      # Get the code first
      - name: "Checkout"
        uses: actions/checkout@v2
      # Then install the AWC CLI tools & boto3
      - name: "Install AWS Cli"
        run: |
          sudo apt-get install python3-setuptools
          pip3 install awscli boto3 zappa virtualenv
      # Run the shell commands using the AWS environment variables
      - name: "Build"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_MOPED_API_ZAPPA_CONFIGURAITON_FILE: ${{ secrets.AWS_MOPED_API_ZAPPA_CONFIGURAITON_FILE }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          source $(pwd)/.github/workflows/aws-moped-api-helper.sh
          deploy_moped_api
