name: "Build eCapris statuses ETL Docker image and push to DockerHub"
on:
  push:
    branches:
      - main
      - production
    paths:
      - ".github/workflows/etl_ecapris_statuses_docker.yml"
      - "moped-etl/ecapris-statuses/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build eCapris status sync ETL docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: atddocker/atd-moped-etl-ecapris-statuses:${{ github.ref_name }}
          context: ./moped-etl/ecapris-statuses
