name: "Reveal"

on:
  workflow_dispatch:
    inputs:
      description:
        default: ""

jobs:
  build_editor:
    name: Build Editor
    runs-on: ubuntu-latest
    steps:
      - name: "Reveal"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MOPED_PRNUM: ${{ github.event.pull_request.number }}
          MOPED_PRBODY: ${{ github.event.pull_request.body }}
          AWS_MOPED_HASURA_CONFIGURAITON_FILE_PRODUCTION: ${{ secrets.AWS_MOPED_HASURA_CONFIGURAITON_FILE_PRODUCTION }}
          AWS_MOPED_HASURA_CONFIGURAITON_FILE_STAGING: ${{ secrets.AWS_MOPED_HASURA_CONFIGURAITON_FILE_STAGING }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "Moped Test Build @ ${BRANCH_NAME}: ${{ github.event.inputs.description }}"
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "MOPED_PRNUM: ${MOPED_PRNUM}"
          echo "PWD: $(pwd)"
          echo "Node Version: $(node --version)"
          echo " NPM Version: $(npm --version)"
          echo "staging: ${AWS_MOPED_HASURA_CONFIGURAITON_FILE_STAGING}"
          echo "production: ${AWS_MOPED_HASURA_CONFIGURAITON_FILE_PRODUCTION}"